// Auto-generated from FastAPI OpenAPI Schema & Frontend Domain Contract — DO NOT EDIT DIRECTLY
// Generated by scripts/export_openapi.py

export interface ModelMetadata {
  provider: string;
  mode: "reasoning" | "degraded_factual";
  model: string;
  fallback_used: boolean;
  fallback_reason?: string;
  reasoning_available: boolean;
  actions_available: boolean;
  latency_ms?: number;
}

export interface ScoreBreakdown {
  impact: number;
  urgency: number;
  evidence_strength: number;
  strategic_relevance: number;
  novelty: number;
  routing_relevance: number;
  total_score: number;
  reason?: string;
}

export interface SignalSource {
  id: string;
  name: string;
  type: string;
  credibility: number;
  url?: string;
}

export interface Signal {
  signal_id?: string;
  source_id?: string;
  development_id?: string;
  pipeline_run_id?: string;
  pmid?: string;
  nct_id?: string;
  regulatory_id?: string;
  fingerprint?: string;
  canonical_url?: string;
  signal_type?: string;
  disease?: string;
  title: string;
  content?: string;
  published_at?: string;
  retrieved_at?: string;
  facts?: string[];
  interpretation?: string;
  speculation?: string;
  priority?: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
  score_breakdown?: ScoreBreakdown;
  model_metadata?: ModelMetadata;
  scoring_model_version?: string;
  scoring_config_version?: string;
  embedding_model_version?: string;
  prompt_version?: string;
  created_at?: string;

  // Frontend UI & Dashboard properties
  id: string;
  summary: string;
  severity: "critical" | "high" | "medium" | "low" | "neutral";
  status: string;
  score: number;
  confidence: number;
  detectedAt: string;
  tags?: string[];
  sources: SignalSource[];
  stakeholders: Record<string, number>;
}

export interface Development {
  development_id: string;
  title: string;
  disease: string;
  asset_id?: string;
  company_id?: string;
  current_stage: string;
  created_at: string;
  updated_at: string;
}

export interface HealthResponse {
  status: string;
  service: string;
  version: string;
  timestamp: string;
}

export interface HealthReadyResponse {
  status: "ready" | "degraded";
  database: boolean;
  redis: boolean;
  redis_warning?: string;
  timestamp: string;
}

export interface HealthModelsResponse {
  llm_provider: string;
  ollama_host: string;
  gemma_available: boolean;
  grok_configured: boolean;
  grok_fallback_enabled: boolean;
  bart_degraded_available: boolean;
  embedding_model: string;
  embedding_revision: string;
  embedding_dimension: number;
}

export interface SignalSearchResult {
  signal_id: string;
  title: string;
  content: string;
  signal_type: string;
  disease: string;
  priority: string;
  similarity_score: number;
  embedding_model_version?: string;
  created_at?: string;
}

export interface SearchFilters {
  signal_type?: string;
  disease?: string;
  priority?: string;
}

export interface SearchRequest {
  query: string;
  filters?: SearchFilters;
  top_k?: number;
  ef_search?: number;
}

export interface SearchResponse {
  results: SignalSearchResult[];
  total: number;
  query: string;
  ef_search_used: number;
}

export interface ConnectorHealthStatus {
  source_id: string;
  name: string;
  status: string;
  freshness_class: string;
  quota_remaining?: number;
  last_success?: string;
  last_error?: string;
}

export interface HealthConnectorsResponse {
  connectors: ConnectorHealthStatus[];
  timestamp: string;
}

export interface PipelineRunRequest {
  batch_size?: number;
  calibration_weights?: Record<string, number>;
}

export interface PipelineRunResponse {
  pipeline_run_id: string;
  status: string;
  signals_processed: number;
  role_briefs_count: number;
  developments_count: number;
  confluence_stories_count: number;
  contradictions_count: number;
  missing_signals_count: number;
  node_statuses: Record<string, string>;
  errors: Array<Record<string, any>>;
  timestamp: string;
}

// Frontend Dashboard & Athena UI Types
export interface AthenaResponse {
  answer: string;
  confidence: number;
  sources: SignalSource[];
}

export interface TrendPoint {
  label: string;
  value: number;
  baseline?: number;
}

export interface ConfluenceSummary {
  score: number;
  label: string;
  drivers: string[];
  updatedAt: string;
}

export interface LifecycleSummary {
  id: string;
  name: string;
  stage: string;
  momentum: number;
  confidence: number;
  lastChanged: string;
  signals: number;
}

export interface DashboardHealth {
  api: string;
  lastSync: string;
  latencyMs: number;
  sourceCount: number;
}

export interface DashboardOverview {
  active_signals?: number;
  monitored_assets?: number;
  confluences_detected?: number;
  contradictions_flagged?: number;
  weekly_change?: string;
  signals: Signal[];
  confluence: ConfluenceSummary;
  lifecycle: LifecycleSummary[];
  trends: TrendPoint[];
  health: DashboardHealth;
}

export type HealthStatus = DashboardHealth;
