// Auto-generated from FastAPI OpenAPI Schema — DO NOT EDIT DIRECTLY
// Generated by scripts/export_openapi.py

export interface ModelMetadata {
  provider: string;
  mode: "reasoning" | "degraded_factual";
  model: string;
  fallback_used: boolean;
  fallback_reason?: string;
  reasoning_available: boolean;
  actions_available: boolean;
  latency_ms?: number;
}

export interface ScoreBreakdown {
  impact: number;
  urgency: number;
  evidence_strength: number;
  strategic_relevance: number;
  novelty: number;
  routing_relevance: number;
  total_score: number;
  reason?: string;
}

export interface Signal {
  signal_id: string;
  source_id: string;
  development_id?: string;
  pipeline_run_id?: string;
  pmid?: string;
  nct_id?: string;
  regulatory_id?: string;
  fingerprint: string;
  canonical_url?: string;
  signal_type: string;
  disease: string;
  title: string;
  content: string;
  published_at: string;
  retrieved_at: string;
  facts: string[];
  interpretation?: string;
  speculation?: string;
  priority: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
  score_breakdown?: ScoreBreakdown;
  model_metadata?: ModelMetadata;
  scoring_model_version: string;
  scoring_config_version: string;
  embedding_model_version: string;
  prompt_version: string;
  created_at: string;
}

export interface Development {
  development_id: string;
  title: string;
  disease: string;
  asset_id?: string;
  company_id?: string;
  current_stage: string;
  created_at: string;
  updated_at: string;
}

export interface HealthResponse {
  status: string;
  service: string;
  version: string;
  timestamp: string;
}

export interface HealthReadyResponse {
  status: "ready" | "degraded";
  database: boolean;
  redis: boolean;
  redis_warning?: string;
  timestamp: string;
}

export interface HealthModelsResponse {
  llm_provider: string;
  gemma_available: bool;
  grok_configured: bool;
  grok_fallback_enabled: bool;
  bart_degraded_available: bool;
  embedding_model: string;
  embedding_revision: string;
  embedding_dimension: number;
}

export interface ConnectorHealthStatus {
  source_id: string;
  name: string;
  status: string;
  freshness_class: string;
  quota_remaining?: number;
  last_success?: string;
  last_error?: string;
}

export interface HealthConnectorsResponse {
  connectors: ConnectorHealthStatus[];
  timestamp: string;
}
