'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { usePathname } from 'next/navigation'
import { AnimatePresence, motion } from 'framer-motion'
import { Activity, Bell, BookOpen, BrainCircuit, ChevronRight, CircleHelp, FlaskConical, Gauge, LayoutDashboard, Menu, Moon, Network, PanelLeft, Search, Settings, ShieldCheck, Sparkles, Sun, Target, X } from 'lucide-react'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { askAthena, getOverview } from '@/lib/api'
import type { DashboardOverview, Signal } from '@/types/api'

const nav = [
  { href: '/dashboard', label: 'Overview', icon: LayoutDashboard }, { href: '/signals', label: 'Signals', icon: Activity }, { href: '/developments', label: 'Developments', icon: FlaskConical }, { href: '/intelligence', label: 'Intelligence', icon: BrainCircuit }, { href: '/functions', label: 'Functions', icon: Network }, { href: '/calibrate', label: 'Calibrate', icon: Gauge },
]
const secondary = [{ href: '/sources', label: 'Sources', icon: BookOpen }, { href: '/settings', label: 'Settings', icon: Settings }]

function Badge({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: 'critical' | 'high' | 'medium' | 'low' | 'neutral' }) { return <span className={`badge badge-${tone}`}>{children}</span> }
function Card({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <section className={`panel ${className}`}>{children}</section> }
function SectionTitle({ eyebrow, title, detail }: { eyebrow: string; title: string; detail?: string }) { return <div className="section-title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{detail && <p className="muted max-w-xs text-right text-sm">{detail}</p>}</div> }

export function Shell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const [open, setOpen] = useState(false); const [dark, setDark] = useState(true)
  useEffect(() => { document.documentElement.classList.toggle('dark', dark) }, [dark])
  const links = [...nav, ...secondary]
  return <div className="app-shell">
    <aside className={`sidebar ${open ? 'sidebar-open' : ''}`}>
      <div className="brand"><div className="brand-mark"><Target size={18} /></div><div><strong>MetaRadar</strong><span>Decision intelligence</span></div><button className="icon-button sidebar-close" onClick={() => setOpen(false)} aria-label="Close navigation"><X size={18} /></button></div>
      <div className="workspace"><span className="status-dot" /> Haemophilia / Global <ChevronRight size={14} /></div>
      <nav className="nav-list" aria-label="Primary navigation">{links.map(({ href, label, icon: Icon }) => <Link key={href} href={href} onClick={() => setOpen(false)} className={`nav-item ${pathname === href ? 'active' : ''}`}><Icon size={17} /><span>{label}</span>{label === 'Signals' && <span className="nav-count">12</span>}</Link>)}</nav>
      <div className="sidebar-note"><Sparkles size={17} /><div><strong>Synthetic signal environment</strong><span>1,264 synthetic records</span></div></div>
      <div className="profile"><div className="avatar">SL</div><div><strong>Strategic lead</strong><span>Workspace role</span></div><ChevronRight size={15} /></div>
    </aside>
    <div className="main-column">
      <header className="topbar"><button className="icon-button menu-button" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={20} /></button><div className="breadcrumbs"><span>Workspace</span><ChevronRight size={14} /><strong>{nav.find((item) => item.href === pathname)?.label ?? secondary.find((item) => item.href === pathname)?.label ?? 'Overview'}</strong></div><div className="top-actions"><button className="search-button"><Search size={16} /><span>Search signals</span><kbd>⌘ K</kbd></button><button className="icon-button notification" aria-label="Notifications"><Bell size={17} /><i /></button><button className="theme-toggle" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? <Moon size={16} /> : <Sun size={16} />}</button></div></header>
      <main className="content">{children}</main>
      <footer className="health-footer"><span><ShieldCheck size={15} className="text-emerald" /> Demo environment · Synthetic data</span><span>Last sync {overviewHealth.lastSync}</span><span className="footer-source">Synthetic intelligence · v0.1.0</span></footer>
    </div>
  </div>
}
const overviewHealth = { lastSync: '08:42:18 UTC' }

function KPI({ label, value, change, accent }: { label: string; value: string; change: string; accent?: string }) { return <Card className="kpi"><p className="eyebrow">{label}</p><div className="kpi-value"><strong>{value}</strong><span className={accent ?? 'positive'}>{change}</span></div><div className="micro-bars"><i /><i /><i /><i /><i /></div></Card> }
function Radar({ score }: { score: number }) { return <div className="radar"><div className="radar-ring ring-one" /><div className="radar-ring ring-two" /><div className="radar-ring ring-three" /><div className="radar-sweep" /><div className="radar-core"><strong>{score}</strong><span>confluence</span></div></div> }
function SignalRow({ signal, onSelect }: { signal: Signal; onSelect: (signal: Signal) => void }) { return <button className="signal-row" onClick={() => onSelect(signal)}><span className={`severity-dot ${signal.severity}`} /><div className="signal-copy"><div><strong>{signal.title}</strong><Badge tone={signal.severity}>{signal.severity}</Badge></div><span>{signal.summary}</span><small>{signal.detectedAt} · {signal.sources.length} sources</small></div><div className="signal-score"><strong>{signal.score}</strong><span>priority score</span></div><ChevronRight size={17} className="muted" /></button> }
function TrendChart({ data }: { data: DashboardOverview['trends'] }) { return <div className="chart-wrap"><ResponsiveContainer width="100%" height={220}><AreaChart data={data} margin={{ left: -22, right: 8, top: 10, bottom: 0 }}><defs><linearGradient id="trend" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--signal)" stopOpacity={0.35} /><stop offset="100%" stopColor="var(--signal)" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 11 }} /><YAxis hide domain={[0, 100]} /><Tooltip contentStyle={{ background: 'var(--panel)', border: '1px solid var(--border)', borderRadius: 10, color: 'var(--foreground)' }} /><Area type="monotone" dataKey="baseline" stroke="var(--muted-foreground)" strokeDasharray="4 4" fill="none" strokeWidth={1.5} /><Area type="monotone" dataKey="value" stroke="var(--signal)" fill="url(#trend)" strokeWidth={2.5} /></AreaChart></ResponsiveContainer></div> }

export function DashboardPage() {
  const [data, setData] = useState<DashboardOverview | null>(null); const [selected, setSelected] = useState<Signal | null>(null)
  useEffect(() => { getOverview().then(setData) }, [])
  if (!data) return <Loading />
  return <><SectionTitle eyebrow="Portfolio pulse" title="Good morning" detail="The signal landscape is moving with unusual alignment." /><div className="synthetic-banner"><Activity size={16} /><span>All intelligence shown is synthetic and for interface demonstration only.</span><Badge>DEMO DATA</Badge></div><div className="kpi-grid"><KPI label="Active signals" value="38" change="+12.4%" /><KPI label="Confluence index" value="78" change="+8.1%" /><KPI label="Time to decision" value="4.6d" change="−0.8d" /><KPI label="Source coverage" value="94%" change="+2.7%" /></div><div className="bento-grid"><Card className="signals-panel priority-intelligence"><div className="card-heading"><div><p className="eyebrow">Priority intelligence</p><h2>Signals requiring attention</h2><p className="muted panel-subtitle">Independent evidence converging on the next decision.</p></div><Link href="/signals" className="text-link">View all <ChevronRight size={15} /></Link></div><div className="signal-list">{data.signals.slice(0, 3).map((signal) => <SignalRow key={signal.id} signal={signal} onSelect={setSelected} />)}</div></Card><Card className="radar-panel"><div className="card-heading"><div><p className="eyebrow">Cross-source alignment</p><h2>Confluence index</h2><p className="muted confluence-explainer">Independent signals pointing to the same development.</p></div><CircleHelp size={16} className="muted" /></div><Radar score={data.confluence.score} /><div className="driver-list">{data.confluence.drivers.map((driver, index) => <div key={driver}><span className="driver-number">0{index + 1}</span><span>{['TRIAL READOUT', 'REGULATORY SIGNAL', 'PUBLICATION', 'PATIENT / ACCESS'][index] ?? driver}</span><span className="driver-line" /><small>{driver}</small></div>)}</div></Card><Card className="trend-panel"><div className="card-heading"><div><p className="eyebrow">Signal velocity</p><h2>Portfolio momentum</h2></div><Badge tone="high">+24%</Badge></div><TrendChart data={data.trends} /></Card><Card className="questions-panel"><div className="card-heading"><div><p className="eyebrow">Decision frame</p><h2>Four questions</h2></div><Link href="/intelligence" className="icon-link"><ChevronRight size={17} /></Link></div>{['What changed?', 'Why does it matter?', 'Who is affected?', 'What should we do?'].map((q, i) => <Link href="/intelligence" className="question-row" key={q}><span>Q{i + 1}</span><strong>{q}</strong><ChevronRight size={15} /></Link>)}</Card></div>{selected && <SignalDrawer signal={selected} onClose={() => setSelected(null)} />}</>
}
function SignalDrawer({ signal, onClose }: { signal: Signal; onClose: () => void }) { return <div className="drawer-backdrop" onClick={onClose}><motion.aside initial={{ x: 30, opacity: 0 }} animate={{ x: 0, opacity: 1 }} className="signal-drawer" onClick={(event) => event.stopPropagation()}><div className="drawer-top"><Badge tone={signal.severity}>{signal.severity} signal</Badge><button className="icon-button" onClick={onClose} aria-label="Close signal"><X size={18} /></button></div><p className="eyebrow">{signal.id} · {signal.detectedAt}</p><h2>{signal.title}</h2><div className="drawer-sections"><div><h3>What changed?</h3><p>{signal.summary}</p></div><div><h3>Why does it matter?</h3><p>This signal may change the current development outlook and deserves cross-functional review.</p></div><div><h3>Who should review?</h3><p>{Object.keys(signal.stakeholders).join(' · ') || 'Medical Affairs · Regulatory · Leadership'}</p></div><div><h3>What action may be required?</h3><p>Validate the evidence, compare related signals, and route to the accountable function.</p></div></div><div className="drawer-score"><strong>{signal.score}</strong><span>priority score</span><strong>{signal.confidence}%</strong><span>relevance confidence</span></div><h3>Evidence & provenance</h3><p className="muted evidence-note">Source material supporting this intelligence.</p>{signal.sources.map((source) => <div className="source-line" key={source.id}><BookOpen size={15} /><span><strong>{source.name}</strong><small>{source.type} · published / retrieved</small></span><Badge>{source.credibility}%</Badge><ChevronRight size={14} /></div>)}<div className="drawer-followup"><h3>Watch next</h3><p>Look for confirming evidence across the next source refresh.</p></div></motion.aside></div> }

export function SignalsPage() { const [data, setData] = useState<DashboardOverview | null>(null); const [filter, setFilter] = useState('all'); const [selected, setSelected] = useState<Signal | null>(null); useEffect(() => { getOverview().then(setData) }, []); const filtered = useMemo(() => data?.signals.filter((s) => filter === 'all' || s.severity === filter) ?? [], [data, filter]); if (!data) return <Loading />; return <><SectionTitle eyebrow="Live intelligence stream" title="Signals" detail="A ranked view of meaningful change across the haemophilia landscape." /><div className="signals-toolbar"><div className="filter-bar">{['all', 'critical', 'high', 'medium', 'low'].map((item) => <button key={item} className={filter === item ? 'filter-active' : ''} onClick={() => setFilter(item)}>{item === 'all' ? 'All signals' : item}</button>)}</div><Card className="filtered-view"><p className="eyebrow">Filtered view</p><div className="filtered-stats"><strong>{filtered.length}<span>visible</span></strong><strong>{filtered.filter((signal) => signal.severity === 'high' || signal.severity === 'critical').length}<span>high priority</span></strong><strong>{filtered.reduce((total, signal) => total + signal.sources.length, 0)}<span>sources</span></strong><strong>08:42<span>last updated</span></strong></div><p className="muted">Active filter: {filter === 'all' ? 'All signals' : filter}</p></Card></div><Card><div className="signal-list">{filtered.map((signal) => <SignalRow key={signal.id} signal={signal} onSelect={setSelected} />)}</div></Card>{selected && <SignalDrawer signal={selected} onClose={() => setSelected(null)} />}</> }

export function IntelligencePage() { const [prompt, setPrompt] = useState(''); const [answer, setAnswer] = useState<{ answer: string; confidence: number } | null>(null); const [loading, setLoading] = useState(false); const prompts = ['What changed in access this week?', 'Which signals have the strongest confluence?', 'Where should we validate next?']; async function submit(value = prompt) { if (!value.trim()) return; setPrompt(value); setLoading(true); setAnswer(null); setAnswer(await askAthena(value)); setLoading(false) } return <><SectionTitle eyebrow="Strategic synthesis" title="Intelligence" detail="Ask Athena to connect signals into a decision-ready point of view." /><div className="intelligence-grid"><Card className="athena-card"><div className="athena-orbit"><BrainCircuit size={30} /></div><p className="eyebrow">Athena synthesis layer</p><h2>Make the next signal useful.</h2><p className="muted">Explore the evidence behind the pulse, then turn a pattern into a clear next step.</p><div className="prompt-list">{prompts.map((item) => <button key={item} onClick={() => submit(item)}>{item}<ChevronRight size={15} /></button>)}</div><div className="ask-row"><input value={prompt} onChange={(e) => setPrompt(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') submit() }} placeholder="Ask a strategic question..." /><button onClick={() => submit()} disabled={loading}><Sparkles size={16} /> {loading ? 'Thinking' : 'Ask Athena'}</button></div></Card><Card className="answer-card"><p className="eyebrow">Response</p>{loading ? <div className="thinking"><i /><i /><i /></div> : answer ? <><h2>Here&apos;s the read.</h2><p>{answer.answer}</p><div className="confidence"><span>Confidence</span><strong>{answer.confidence}%</strong></div></> : <div className="empty-state"><BrainCircuit size={24} /><p>Select a prompt to begin a synthesis.</p><span>Athena can connect evidence, compare confluence, and frame the next review.</span><small>Recent synthesis: none in this demo workspace.</small></div>}</Card></div></> }

export function GenericPage({ title, eyebrow, description, children }: { title: string; eyebrow: string; description: string; children?: React.ReactNode }) { return <><SectionTitle eyebrow={eyebrow} title={title} detail={description} /><div className="generic-grid"><Card><div className="placeholder-visual"><Network size={26} /><strong>Signal architecture</strong><span>Connected evidence will appear here.</span></div></Card><Card><p className="eyebrow">System note</p><h2>Build from the evidence.</h2><p className="muted">This workspace is ready for review workflows, provenance, and role-specific decisions.</p>{children}</Card></div></> }
function Loading() { return <div className="loading-screen"><div className="loading-mark"><Activity size={22} /></div><p>Loading signal landscape</p></div> }
