import json
import os
import sys
from pathlib import Path

# Add backend directory to sys.path
base_dir = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(base_dir / "backend"))

from app.main import app


def export_contracts():
    """Exports OpenAPI JSON and generates canonical TypeScript API contract in frontend/types/api.ts."""
    openapi_schema = app.openapi()
    
    # 1. Export contracts/openapi.json
    contracts_dir = base_dir / "contracts"
    contracts_dir.mkdir(exist_ok=True)
    
    json_path = contracts_dir / "openapi.json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(openapi_schema, f, indent=2)
    print(f"Exported OpenAPI JSON schema to: {json_path}")

    # 2. Export canonical frontend/types/api.ts
    active_types_dir = base_dir / "frontend" / "types"
    active_types_dir.mkdir(parents=True, exist_ok=True)

    ts_content = """// Auto-generated from FastAPI OpenAPI Schema & Frontend Domain Contract — DO NOT EDIT DIRECTLY
// Generated by scripts/export_openapi.py

export interface ModelMetadata {
  provider: string;
  mode: "reasoning" | "degraded_factual";
  model: string;
  fallback_used: boolean;
  fallback_reason?: string;
  reasoning_available: boolean;
  actions_available: boolean;
  latency_ms?: number;
}

export interface ScoreBreakdown {
  impact: number;
  urgency: number;
  evidence_strength: number;
  strategic_relevance: number;
  novelty: number;
  routing_relevance: number;
  total_score: number;
  reason?: string;
}

export interface SignalSource {
  id: string;
  name: string;
  type: string;
  credibility: number;
  url?: string;
}

export interface Signal {
  signal_id?: string;
  source_id?: string;
  development_id?: string;
  pipeline_run_id?: string;
  pmid?: string;
  nct_id?: string;
  regulatory_id?: string;
  fingerprint?: string;
  canonical_url?: string;
  signal_type?: string;
  disease?: string;
  title: string;
  content?: string;
  published_at?: string;
  retrieved_at?: string;
  facts?: string[];
  interpretation?: string;
  speculation?: string;
  priority?: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
  score_breakdown?: ScoreBreakdown;
  model_metadata?: ModelMetadata;
  scoring_model_version?: string;
  scoring_config_version?: string;
  embedding_model_version?: string;
  prompt_version?: string;
  created_at?: string;

  // Frontend UI & Dashboard properties
  id: string;
  summary: string;
  severity: "critical" | "high" | "medium" | "low" | "neutral";
  status: string;
  score: number;
  confidence: number;
  detectedAt: string;
  tags?: string[];
  sources: SignalSource[];
  stakeholders: Record<string, number>;
}

export interface Development {
  development_id: string;
  title: string;
  disease: string;
  asset_id?: string;
  company_id?: string;
  current_stage: string;
  created_at: string;
  updated_at: string;
}

export interface HealthResponse {
  status: string;
  service: string;
  version: string;
  timestamp: string;
}

export interface HealthReadyResponse {
  status: "ready" | "degraded";
  database: boolean;
  redis: boolean;
  redis_warning?: string;
  timestamp: string;
}

export interface HealthModelsResponse {
  llm_provider: string;
  ollama_host: string;
  gemma_available: boolean;
  grok_configured: boolean;
  grok_fallback_enabled: boolean;
  bart_degraded_available: boolean;
  embedding_model: string;
  embedding_revision: string;
  embedding_dimension: number;
}

export interface SignalSearchResult {
  signal_id: string;
  title: string;
  content: string;
  signal_type: string;
  disease: string;
  priority: string;
  similarity_score: number;
  embedding_model_version?: string;
  created_at?: string;
}

export interface SearchFilters {
  signal_type?: string;
  disease?: string;
  priority?: string;
}

export interface SearchRequest {
  query: string;
  filters?: SearchFilters;
  top_k?: number;
  ef_search?: number;
}

export interface SearchResponse {
  results: SignalSearchResult[];
  total: number;
  query: string;
  ef_search_used: number;
}

export interface ConnectorHealthStatus {
  source_id: string;
  name: string;
  status: string;
  freshness_class: string;
  quota_remaining?: number;
  last_success?: string;
  last_error?: string;
}

export interface HealthConnectorsResponse {
  connectors: ConnectorHealthStatus[];
  timestamp: string;
}

export interface PipelineRunRequest {
  batch_size?: number;
  calibration_weights?: Record<string, number>;
}

export interface PipelineRunResponse {
  pipeline_run_id: string;
  status: string;
  signals_processed: number;
  role_briefs_count: number;
  developments_count: number;
  confluence_stories_count: number;
  contradictions_count: number;
  missing_signals_count: number;
  node_statuses: Record<string, string>;
  errors: Array<Record<string, any>>;
  timestamp: string;
}

// Frontend Dashboard & Athena UI Types
export interface AthenaResponse {
  answer: string;
  confidence: number;
  sources: SignalSource[];
}

export interface TrendPoint {
  label: string;
  value: number;
  baseline?: number;
}

export interface ConfluenceSummary {
  score: number;
  label: string;
  drivers: string[];
  updatedAt: string;
}

export interface LifecycleSummary {
  id: string;
  name: string;
  stage: string;
  momentum: number;
  confidence: number;
  lastChanged: string;
  signals: number;
}

export interface DashboardHealth {
  api: string;
  lastSync: string;
  latencyMs: number;
  sourceCount: number;
}

export interface DashboardOverview {
  active_signals?: number;
  monitored_assets?: number;
  confluences_detected?: number;
  contradictions_flagged?: number;
  weekly_change?: string;
  signals: Signal[];
  confluence: ConfluenceSummary;
  lifecycle: LifecycleSummary[];
  trends: TrendPoint[];
  health: DashboardHealth;
}

export type HealthStatus = DashboardHealth;

// Phase 5 Calibration & Feedback Types
export interface FeedbackSubmissionRequest {
  signal_id: string;
  stakeholder_function: string;
  relevance_rating: number;
  urgency_rating: number;
  action_appropriate: boolean;
  comments?: string;
  user_id?: string;
}

export interface FeedbackSubmissionResponse {
  feedback_id: string;
  signal_id: string;
  stakeholder_function: string;
  status: string;
  unapplied_count: number;
  recalibration_triggered: boolean;
}

export interface RoleWeight {
  stakeholder_function: string;
  impact_weight: number;
  urgency_weight: number;
  novelty_weight: number;
  updated_at: string;
}

export interface CalibrationWeightsResponse {
  version: string;
  weights: RoleWeight[];
}

export interface WatchRuleSuggestion {
  suggestion_id: string;
  development_id?: string;
  trigger_event: string;
  expected_event: string;
  monitoring_window_days: number;
  responsible_function: string;
  rationale: string;
}

export interface BeforeAfterComparison {
  signal_id: string;
  stakeholder_function: string;
  baseline_priority: string;
  calibrated_priority: string;
  baseline_relevance_score: number;
  calibrated_relevance_score: number;
  baseline_suggested_action: string;
  calibrated_suggested_action: string;
  confidence_uplift_pct: number;
}

export interface RecalibrateResponse {
  status: string;
  calibration_version: string;
  stakeholder_function?: string;
  applied_feedback_count: number;
  updated_weights: RoleWeight[];
  comparisons: BeforeAfterComparison[];
  watch_rule_suggestions: WatchRuleSuggestion[];
}

export interface FeedbackRoleSummary {
  stakeholder_function: string;
  total_feedback_count: number;
  average_relevance: number;
  average_urgency: number;
  action_approval_rate: number;
}

export interface FeedbackSummaryResponse {
  total_feedback: number;
  roles: FeedbackRoleSummary[];
}

export interface ConfirmWatchItemRequest {
  development_id: string;
  trigger_event: string;
  expected_event: string;
  monitoring_window_days?: number;
  responsible_function: string;
}

export interface ConfirmWatchItemResponse {
  watch_id: string;
  status: string;
  responsible_function: string;
  monitoring_window_days: number;
}
"""

    active_ts_path = active_types_dir / "api.ts"
    with open(active_ts_path, "w", encoding="utf-8") as f:
        f.write(ts_content)
    print(f"Exported canonical TypeScript API types to: {active_ts_path}")

    # 3. Write re-export stub to legacy location frontend/src/types/api.ts
    legacy_types_dir = base_dir / "frontend" / "src" / "types"
    legacy_types_dir.mkdir(parents=True, exist_ok=True)
    legacy_ts_path = legacy_types_dir / "api.ts"
    with open(legacy_ts_path, "w", encoding="utf-8") as f:
        f.write("// Re-export canonical contract definition\nexport * from '../../types/api';\n")
    print(f"Updated legacy contract pointer: {legacy_ts_path}")


if __name__ == "__main__":
    export_contracts()
